___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from scipy import stats
from pandas import Series, DataFrame

#### 2. Create an array from my_list=[5,10,15,20,25]

In [2]:
my_list=[5,10,15,20,25]

arr = np.array(my_list)
arr

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [3]:
arr = np.zeros((5,5))
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# addition
arr = np.ones((5,5))*0
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [5]:
arr = np.ones((4,4),dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [6]:
# addition
arr = np.zeros((4,4),dtype=int)+1
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### 5. Make all the values of the array above 7

In [7]:
arr = np.ones((4,4),dtype=int)*7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [8]:
# addition
arr = np.zeros((4,4),dtype=int)+7
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 6. Create thr previous array above by full() method

In [9]:
arr = np.full((4,4),7)
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [10]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [11]:
# addition
np.linspace(2,16,8,dtype=int)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [12]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
# addition
arr = np.full((25,), [i for i in range(25)]).reshape(5,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [14]:
np.linspace(0,24,25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [15]:
np.random.rand(5)

array([0.71510971, 0.24298075, 0.27600949, 0.0749541 , 0.68371675])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [16]:
a = np.random.randn(5,5)
a

array([[-0.91390743, -0.67440844,  0.31170847, -1.01971102, -0.55255929],
       [ 0.35879861,  0.20151765,  1.17276015,  1.31248066, -0.62791837],
       [ 0.00727464,  1.44099704,  0.92763151, -0.26074557, -1.44813578],
       [-0.29850342,  0.20521373,  0.28855245, -0.53235516, -0.45715819],
       [ 0.05435913,  1.8577799 ,  0.56883995,  0.23639088, -0.10184666]])

In [17]:
a.mean()

0.08228221661004213

In [18]:
np.median(a), np.percentile(a, 50)

(0.0543591272955237, 0.0543591272955237)

In [19]:
a.std(), np.sqrt(a.var())

(0.7969393370192638, 0.7969393370192638)

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [20]:
np.random.randint(20,50,(3,4))

array([[29, 30, 41, 20],
       [22, 27, 41, 38],
       [42, 44, 24, 27]])

In [21]:
# addition
np.linspace(20,50,12,dtype=int).reshape(3,4)

array([[20, 22, 25, 28],
       [30, 33, 36, 39],
       [41, 44, 47, 50]])

In [22]:
# addition
np.random.rand(3,4)//0.1+20

array([[22., 28., 22., 20.],
       [22., 29., 21., 29.],
       [22., 22., 22., 23.]])

In [23]:
# addition
np.random.random((3,4))//0.05+20

array([[25., 23., 26., 30.],
       [27., 26., 33., 31.],
       [35., 22., 22., 34.]])

In [24]:
# addition------not -useful in this
np.random.randn(3,4)//0.05

array([[ 13., -16., -10., -24.],
       [ -5.,  -1., -17., -12.],
       [-26.,  14.,  16.,   3.]])

#### 13. Reshape the array below with the shape of 6x8

In [25]:
ranarr = np.array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [26]:
ranarr

array([52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8, 44,  2, 46, 27, 11,
       29, 30, 26,  8, 49, 19,  2,  9, 38, 40, 36, 16, 41, 39, 17, 20, 42,
       23, 35, 45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52])

In [27]:
ranarr = ranarr.reshape(6,8)
ranarr

array([[52, 48, 21, 29, 15, 35,  3, 29],
       [43, 48, 38,  8, 44,  2, 46, 27],
       [11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17],
       [20, 42, 23, 35, 45, 18, 40,  9],
       [36, 37,  5, 17, 44, 36,  2, 52]])

In [28]:
ranarr.reshape(4,12)  # exchange same len size possible (48)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

In [29]:
#reshape with -1
ranarr.reshape(-1).reshape(4,12)

array([[52, 48, 21, 29, 15, 35,  3, 29, 43, 48, 38,  8],
       [44,  2, 46, 27, 11, 29, 30, 26,  8, 49, 19,  2],
       [ 9, 38, 40, 36, 16, 41, 39, 17, 20, 42, 23, 35],
       [45, 18, 40,  9, 36, 37,  5, 17, 44, 36,  2, 52]])

## Numpy Indexing and Selection


In [30]:
#Create array below
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [31]:
# addition
np.linspace(1,16,16,dtype=int).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [32]:
# slicing
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [33]:
# Combined slicing-Fancy Indexing
mat[[1,2],1:3]

array([[ 6,  7],
       [10, 11]])

In [34]:
# Fancy Indexing
# addition------not -useful in this
mat[[1,2],[1,2]]

array([ 6, 11])

#### 15. Get the first column of the array above.

In [35]:
mat[:, 0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [36]:
mat[1, ::2]

array([5, 7])

In [37]:
# addition
mat[1, [0,2]]

array([5, 7])

In [38]:
# addition------not -useful in this
mat[1:2, ::2][0]

array([5, 7])

In [39]:
# addition------not -useful in this
mat[1:2, [0,2]][0]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [40]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [41]:
mat[:, 2] = 77
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [42]:
x = mat[1,0]
y = mat[3,1]
np.stack([x,y])

array([ 5, 14])

In [43]:
# addition
mat[[1,3],[0,1]]

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [44]:
mat[1::2, 0::2]

array([[ 5, 77],
       [13, 77]])

In [45]:
# addition
mat[1::2, [0,2]]

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [46]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [47]:
arr_mat = mat[ mat<10 ] + mat[ mat>12 ]
arr_mat

array([78, 79, 81, 18, 20, 85, 25])

In [48]:
# addition
mat<10

array([[ True,  True, False,  True],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [49]:
# addition
mat[ mat<10 ]

array([1, 2, 4, 5, 6, 8, 9])

In [50]:
# addition
mat[ mat>12 ]

array([77, 77, 77, 13, 14, 77, 16])

#### 21. Get the standard deviation of the result above

In [51]:
np.std(arr_mat)

29.700546274093877

In [52]:
# addition
arr_mat.std(), np.sqrt(arr_mat.var())

(29.700546274093877, 29.700546274093877)

#### 22. Get the sum of the second column from array above

In [53]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [54]:
mat[:,1].sum()

32

#### 23. Get the median, mean and std of 3rd row from array above

In [55]:
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
mat[2]

array([ 9, 10, 11, 12])

In [57]:
#mean
mat[2].mean()

10.5

In [58]:
#median
np.median( mat[2] )

10.5

In [59]:
# addition
np.percentile(mat[2], 50)

10.5

In [60]:
#std
mat[2].std()

1.118033988749895

# Pandas Section

In [1]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [123]:
sal = pd.read_csv(r'/Users/saint/Downloads/Salaries 2.csv')
sal

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided        NaN   
148651                                    Not provided        NaN   
148652                                    Not provided        NaN   
148653                      Counselor, Log Cabin Ranch       0.00   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
148649         0.00       0.00       0.0       0.00              0.00  2014   
148650          NaN        NaN       NaN       0.00              0.00  2014   
148651          NaN        NaN       NaN       0.00              0.00  2014   
148652          NaN        NaN       NaN       0.00              0.00  2014   
148653         0.00    -618.13       0.0    -618.13           -618.13  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
148649    NaN  San Francisco     NaN  
148650    NaN  San Francisco     NaN  
148651    NaN  San Francisco     NaN  
148652    NaN  San Francisco     NaN  
148653    NaN  San Francisco     NaN  

[148654 rows x 13 columns]

In [4]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [5]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [6]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

**How many different year values are there?**

In [66]:
sal['Year'].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [67]:
# addition
sal.Year.value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [68]:
# addition
sal.groupby( ['Year'] ).count()['Id']

Year
2011    36159
2012    36766
2013    37606
2014    38123
Name: Id, dtype: int64

In [69]:
# addition
sal.groupby( ['Year'] ).count()['Id'].sort_index(ascending=False)

Year
2014    38123
2013    37606
2012    36766
2011    36159
Name: Id, dtype: int64

**Print out max and avg Totalpay**

In [7]:
#max
sal[ 'TotalPay' ].max()

567595.43

In [71]:
#avg
sal[ 'TotalPay' ].mean()

74768.321971703

In [72]:
# addition
np.average(sal[ 'TotalPay' ])

74768.32197169267

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [73]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [17]:
sal[sal['TotalPay'] >sal[ 'TotalPay' ].mean()]['TotalPay']

0         567595.43
1         538909.28
2         335279.91
3         332343.61
4         326373.19
            ...    
135701     77186.02
135778     76746.22
135847     76305.74
135853     76280.70
136063     74893.70
Name: TotalPay, Length: 69489, dtype: float64

In [15]:
sal[sal['TotalPay'] >sal[ 'TotalPay' ].mean()]['TotalPay'].shape

(69489,)

In [13]:
sal[ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ].shape[0]

69489

In [75]:
# addition
len( sal[ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ] )

69489

In [76]:
# addition
sal[ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ][ 'TotalPay' ].size

69489

In [77]:
# addition
sal[ 'TotalPay' ][ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ].size

69489

In [78]:
# addition
sal[ sal [ 'TotalPay' ] > sal[ 'TotalPay' ].mean() ][ 'TotalPay' ].count()

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [42]:
sal[sal['EmployeeName']=="ALBERT PARDINI"][ 'TotalPayBenefits' ]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [79]:
sal [ sal['EmployeeName']=='ALBERT PARDINI']

Id    EmployeeName                         JobTitle    BasePay  \
2   3  ALBERT PARDINI  CAPTAIN III (POLICE DEPARTMENT)  212739.13   

   OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
2    106088.18   16452.6       NaN  335279.91         335279.91  2011    NaN   

          Agency  Status  
2  San Francisco     NaN

In [80]:
sal [ sal['EmployeeName']=='ALBERT PARDINI'][ 'TotalPayBenefits' ]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [81]:
# addition
sal.loc [ sal['EmployeeName']=='ALBERT PARDINI'][ 'TotalPayBenefits' ]

2    335279.91
Name: TotalPayBenefits, dtype: float64

In [44]:
# addition
sal.loc[2, 'TotalPayBenefits']

335279.91

In [52]:
sal.loc[[2]]

Id    EmployeeName                         JobTitle    BasePay  \
2   3  ALBERT PARDINI  CAPTAIN III (POLICE DEPARTMENT)  212739.13   

   OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  Notes  \
2    106088.18   16452.6       NaN  335279.91         335279.91  2011    NaN   

          Agency  Status  
2  San Francisco     NaN

In [83]:
# addition
sal.iloc[2, 8]

335279.91

**Who is the lowest paid person?**

In [78]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [56]:
sal[sal['TotalPayBenefits']==sal['TotalPayBenefits'].min()][["EmployeeName"]]

EmployeeName
148653    Joe Lopez

In [85]:
sal[ sal['TotalPay']==sal['TotalPay'].min() ]

Id EmployeeName                    JobTitle  BasePay  OvertimePay  \
148653  148654    Joe Lopez  Counselor, Log Cabin Ranch      0.0          0.0   

        OtherPay  Benefits  TotalPay  TotalPayBenefits  Year  Notes  \
148653   -618.13       0.0   -618.13           -618.13  2014    NaN   

               Agency  Status  
148653  San Francisco     NaN

In [86]:
sal[ sal['TotalPay']==sal['TotalPay'].min()]['EmployeeName']

148653    Joe Lopez
Name: EmployeeName, dtype: object

In [63]:
# addition
sal.loc[ sal['TotalPay']==sal['TotalPay'].min(),  ['EmployeeName','JobTitle']]

EmployeeName                    JobTitle
148653    Joe Lopez  Counselor, Log Cabin Ranch

**What are the unique Jobs in dataset?**

In [64]:
sal['JobTitle'].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

In [75]:
sal['JobTitle'].value_counts()

Transit Operator                                  7036
Special Nurse                                     4389
Registered Nurse                                  3736
Public Svc Aide-Public Works                      2518
Police Officer 3                                  2421
                                                  ... 
CHIEF HOUSING INSPECTOR                              1
TRAFFIC SIGNAL OPERATOR                              1
COURT COMPUTER FACILITIES COORDINATOR                1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I       1
VICTIM & WITNESS TECHNICIAN                          1
Name: JobTitle, Length: 2159, dtype: int64

In [66]:
sal['JobTitle'].nunique()

2159

**List 3 the least common Jobs**

In [79]:
sal['JobTitle'].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [80]:
sal[(sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].shape(0)

Id        EmployeeName                      JobTitle    BasePay  \
36159  36160      Gary Altenberg  Lieutenant, Fire Suppression  128808.87   
36160  36161        Gregory Suhr               Chief of Police  302578.00   
36161  36162          Khoa Trinh   Electronic Maintenance Tech  111921.00   
36162  36163  Joanne Hayes-White        Chief, Fire Department  296943.01   
36163  36164   Frederick Binkley     EMT/Paramedic/Firefighter  126863.19   
...      ...                 ...                           ...        ...   
56520  56521        Sue Madrigal     Senior Eligibility Worker   63841.94   
56521  56522   Concepcion Gruber                   Secretary 2   61996.06   
56522  56523         Kerman Chan       Parking Control Officer   55358.50   
56523  56524      Ramon Lafuente       Parking Control Officer   56006.80   
56524  56525      Lai Ping Szeto            Eligibility Worker   61253.05   

       OvertimePay  OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
36159    220909.48  13126.31  44430.12  362844.66         407274.78  2012   
36160         0.00  18974.11  69810.19  321552.11         391362.30  2012   
36161    146415.32  78057.41  53102.29  336393.73         389496.02  2012   
36162         0.00  17816.59  72047.88  314759.60         386807.48  2012   
36163    192424.49  17917.18  44438.25  337204.86         381643.11  2012   
...            ...       ...       ...        ...               ...   ...   
56520         0.00    568.66  29305.51   64410.60          93716.11  2012   
56521      1111.50    624.00  29981.74   63731.56          93713.30  2012   
56522      8539.77   1231.25  28579.83   65129.52          93709.35  2012   
56523      6326.45   2175.24  29192.61   64508.49          93701.10  2012   
56524       988.54   1460.00  29996.77   63701.59          93698.36  2012   

       Notes         Agency  Status  
36159    NaN  San Francisco     NaN  
36160    NaN  San Francisco     NaN  
36161    NaN  San Francisco     NaN  
36162    NaN  San Francisco     NaN  
36163    NaN  San Francisco     NaN  
...      ...            ...     ...  
56520    NaN  San Francisco     NaN  
56521    NaN  San Francisco     NaN  
56522    NaN  San Francisco     NaN  
56523    NaN  San Francisco     NaN  
56524    NaN  San Francisco     NaN  

[20366 rows x 13 columns]

In [82]:
sal[(sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].shape[0]

20366

In [84]:
sal[(sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].count()['TotalPayBenefits']

20366

In [90]:
sal[ (sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())].shape[0]

20366

In [91]:
# addition
len(sal[ (sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())])

20366

In [92]:
# addition
sal[ (sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())]['EmployeeName'].size

20366

In [93]:
# addition
sal[ (sal['Year']==2012) & (sal['TotalPayBenefits']>sal['TotalPayBenefits'].mean())]['EmployeeName'].count()

20366

In [94]:
# answer

**How many people have a title of Manager in their jobs?**

In [101]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [105]:
sal.filter(regex="^MANAGER", axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[148654 rows x 0 columns]

In [107]:
def finder(item):
    if 'MANAGER'.casefold() in item.casefold(): return True
    else: return False

In [108]:
sal[ sal["JobTitle"].apply(finder)]

Id          EmployeeName  \
0            1        NATHANIEL FORD   
83          84        EDWARD REISKIN   
87          88           KEVIN BARRY   
95          96          MIVIC HIROSE   
162        163         JULIE LABONTE   
...        ...                   ...   
147216  147217  Steven D Koneffklatt   
147502  147503    Alice B Villagomez   
147805  147806    Stephen C Laplante   
148150  148151      Shirley M Parker   
148475  148476         James P Horan   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
83      GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  230827.12   
87                                         MANAGER VII   96814.36   
95                                        MANAGER VIII  215180.76   
162                                       MANAGER VIII  207501.20   
...                                                ...        ...   
147216                                     Manager III       0.00   
147502                                      Manager IV    1660.00   
147805                                      Manager II       0.00   
148150                           Real Property Manager       0.00   
148475                                      Manager IV     175.75   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0               0.0  400184.25       NaN  567595.43         567595.43  2011   
83              0.0       0.00       NaN  230827.12         230827.12  2011   
87              0.0  133563.47       NaN  230377.83         230377.83  2011   
95              0.0   12000.00       NaN  227180.76         227180.76  2011   
162             0.0    2903.37       NaN  210404.57         210404.57  2011   
...             ...        ...       ...        ...               ...   ...   
147216          0.0    1890.72    342.03    1890.72           2232.75  2014   
147502          0.0       0.00     16.60    1660.00           1676.60  2014   
147805          0.0     982.62    177.76     982.62           1160.38  2014   
148150          0.0     647.76      0.00     647.76            647.76  2014   
148475          0.0       0.00      1.41     175.75            177.16  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
83        NaN  San Francisco     NaN  
87        NaN  San Francisco     NaN  
95        NaN  San Francisco     NaN  
162       NaN  San Francisco     NaN  
...       ...            ...     ...  
147216    NaN  San Francisco     NaN  
147502    NaN  San Francisco     NaN  
147805    NaN  San Francisco     NaN  
148150    NaN  San Francisco     NaN  
148475    NaN  San Francisco     NaN  

[4110 rows x 13 columns]

In [97]:
# addition
sal["JobTitle"][sal["JobTitle"].apply(finder)].size

4110

In [109]:
sal[ sal["JobTitle"].apply(finder)].shape[0]

4110

In [98]:
# addition
sal[ sal["JobTitle"].apply(lambda x: finder(x))].shape[0]

4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [99]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [98]:
sal_new= sal.iloc[:, [0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [99]:
sal_new3=sal_new.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new3

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

         TotalPay  TotalPayBenefits  
0       567595.43         567595.43  
1       538909.28         538909.28  
2       335279.91         335279.91  
3       332343.61         332343.61  
4       326373.19         326373.19  
...           ...               ...  
148649       0.00              0.00  
148650       0.00              0.00  
148651       0.00              0.00  
148652       0.00              0.00  
148653    -618.13           -618.13  

[148654 rows x 4 columns]

In [93]:
sal_new2= sal.loc[:, 'EmployeeName':'TotalPayBenefits']
sal_new2

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [100]:
sal[ (sal['TotalPayBenefits'].min() < sal['TotalPayBenefits']) & ( sal['TotalPayBenefits']  < sal['TotalPayBenefits'].mean()) ][["EmployeeName"]]

EmployeeName
10806          KWE LEE
10807   MIGUEL CARO JR
10808    JOANNE MORRIS
10809    LAYLA WELBORN
10810          LE BANH
...                ...
148648     Leon Walker
148649   Roy I Tillery
148650    Not provided
148651    Not provided
148652    Not provided

[75649 rows x 1 columns]

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___